version: '3'
services:
  api:
    build: .
    ports:
      - '4000:4000'
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
      PRISMA_SERVICE: ${PRISMA_SERVICE}
      PRISMA_STAGE: ${PRISMA_STAGE}
    command: npm run dev
    volumes:
      - .:/usr/app

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: ${POSTGRES_PORT}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            migrations: true
    depends_on:
      - postgres

  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - '5432:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
